karma_shop/basketapp/urls.py
from django.urls import path
from basketapp import views

app_name = 'basketapp'

urlpatterns = [
    path('', views.basket, name="index"),
    path('add/<int:product_pk>/', views.basket_add, name="add"),
    path('remove/<int:basket_pk>/', views.basket_remove, name="remove"),
]

karma_shop/karma/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from mainapp import views

urlpatterns = [
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('admin/', admin.site.urls),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

karma_shop/mainapp/urls.py
from django.urls import path
from mainapp import views

app_name = 'mainapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('catalog/', views.products, name="catalog"),
    path('catalog/category/<int:category_pk>/', views.category_items, name="category_items"),
    path('catalog/product/<int:product_pk>/', views.product_page, name="product_page"),
]

karma_shop/basketapp/models.py
from django.contrib.auth import get_user_model
from django.db import models

from mainapp.models import Product


class Basket(models.Model):
    user = models.ForeignKey(to=get_user_model(), on_delete=models.CASCADE)
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name="количество", default=0)
    add_datetime = models.DateTimeField(verbose_name="время", auto_now_add=True)

    @property
    def product_cost(self):
        """Get current product cost"""
        return self.product.price * self.quantity

karma_shop/basketapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect

from basketapp.models import Basket
from mainapp.models import Product

from collections import namedtuple


@login_required
def basket(request):
    basket_items = Basket.objects.filter(user=request.user)

    context = dict(
        basket_items=__get_basket_items(basket_items),
        basket_items_total_price=__get_basket_items_total_price(basket_items),
    )
    return render(request, 'basketapp/basket.html', context=context)


@login_required
def basket_add(request, product_pk=None):

    # 1st way:
    # product = get_object_or_404(Product, pk=product_pk)
    # basket_item = request.user.basket_set.filter(product_id=product_pk).first()
    # if not basket_item:
    #     basket_item = Basket(user=request.user, product=product)

    # 2nd way:
    basket_item, _ = Basket.objects.get_or_create(
        user=request.user,
        product_id=product_pk,
    )

    basket_item.quantity += 1
    basket_item.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def basket_remove(request, basket_pk=None):
    print(f"Removed product from basket with id: {basket_pk}")
    # 1st way:
    basket_item = get_object_or_404(Basket, id=basket_pk)
    basket_item.delete()
    # 2nd way:
    # request.user.basket_set.filter(id=basket_pk).delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def __get_basket_items(basket_items):
    products = Product.objects.all()
    items = []
    item = namedtuple('A', ['basket_item', 'product', 'item_total_price'])
    for basket_item in basket_items:
        try:
            product = products.filter(id=basket_item.product_id).first()
            if product:
                item_total_price = basket_item.product_cost
                items.append(item(basket_item, product, item_total_price))
        except ValueError:
            continue
    return items


def __get_basket_items_total_price(basket_items):
    total_price = sum(map(lambda x: x.product_cost, basket_items))
    return total_price

karma_shop/templates/basketapp/basket.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block everything_else %}

<!-- Start Banner Area -->
<section class="banner-area organic-breadcrumb">
    <div class="container">
        <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
            <div class="col-first">
                <h1>Shopping Cart</h1>
                <nav class="d-flex align-items-center">
                    <a href="{% url 'main:index' %}">Home<span class="lnr lnr-arrow-right"></span></a>
                    <a href="">Cart</a>
                </nav>
            </div>
        </div>
    </div>
</section>
<!-- End Banner Area -->

<!--================Cart Area =================-->
<section class="cart_area">
    <div class="container">
        <div class="cart_inner">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Product</th>
                            <th style="text-align:center" scope="col">Price</th>
                            <th style="text-align:center" scope="col">Quantity</th>
                            <th style="text-align:center" scope="col">Delete</th>
                            <th style="text-align:center" scope="col">Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% if basket_items %}
                        {% for basket_item, product, item_total_price in basket_items %}
                            <tr style="text-align:center">
                                <td>
                                    <div class="media">
                                        <div class="d-flex">
                                            <img src="{{ product.image.url }}" alt="">
                                        </div>
                                        <div class="media-body">
                                            <a href="{% url 'mainapp:product_page' product_pk=product.id %}">{{ product.name }}</a>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <h5>${{ product.price|default:0 }}</h5>
                                </td>
                                <td>
                                    <h5>
                                        {{ basket_item.quantity|default:1 }}
                                    </h5>
{#                                    <div class="product_count">#}
{#                                        <input type="number" name="qty" id="sst" min="0" max="{{ product.quantity }}" value="{{ basket_item.quantity|default:1 }}" title="Quantity:"#}
{#                                            class="input-text qty">#}
{#                                        <button onclick="var result = document.getElementById('sst'); var sst = result.value; if( !isNaN( sst )) result.value++;return false;"#}
{#                                            class="increase items-count" type="button"><i class="lnr lnr-chevron-up"></i></button>#}
{#                                        <button onclick="var result = document.getElementById('sst'); var sst = result.value; if( !isNaN( sst ) &amp;&amp; sst > 0 ) result.value--;return false;"#}
{#                                            class="reduced items-count" type="button"><i class="lnr lnr-chevron-down"></i></button>#}
{#                                    </div>#}
                                </td>
                                <td>
                                    <div style="text-align:center">
                                        <a href="{% url 'basket:remove' basket_pk=basket_item.id %}"><img src="{% static 'mainapp/img/dustbin.png' %}" alt=""></a>
                                    </div>
                                </td>
                                <td>
                                    <h5>${{ item_total_price }}</h5>
                                </td>
                            </tr>
                        {% endfor %}
                        {% else %}
                            <tr>
                                <td>
                                    <h3>Your basket is empty =(</h3>
                                </td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                        {% endif %}
                        <tr style="text-align:center">
                            <td></td>
                            <td></td>
                            <td>
                                <h5>Subtotal</h5>
                            </td>
                            <td></td>
                            <td>
                                <h5>${{ basket_items_total_price|default:0 }}</h5>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
<!--================End Cart Area =================-->

{% endblock %}