karma_shop/authapp/urls.py
from django.urls import path
from authapp import views

app_name = 'authapp'

urlpatterns = [
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('register/', views.register, name="register"),
    path('edit/', views.edit, name="edit"),
    path('verify/<email>/<activation_key>', views.verify, name="verify"),
]

karma_shop/basketapp/urls.py
from django.urls import path
from basketapp import views

app_name = 'basketapp'

urlpatterns = [
    path('', views.basket, name="index"),
    path('add/<int:product_pk>/', views.basket_add, name="add"),
    path('remove/<int:basket_pk>/', views.basket_remove, name="remove"),
]

karma_shop/karma/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from mainapp import views

urlpatterns = [
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('admin/', admin.site.urls),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

karma_shop/mainapp/urls.py
from django.urls import path
from mainapp import views

app_name = 'mainapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('catalog/', views.products, name="catalog"),
    path('catalog/category/<int:category_pk>/', views.category_items, name="category_items"),
    path('catalog/product/<int:product_pk>/', views.product_page, name="product_page"),
]

karma_shop/basketapp/models.py
from django.contrib.auth import get_user_model
from django.db import models

from mainapp.models import Product


class Basket(models.Model):
    user = models.ForeignKey(to=get_user_model(), on_delete=models.CASCADE)
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name="количество", default=0)
    add_datetime = models.DateTimeField(verbose_name="время", auto_now_add=True)

    @property
    def product_cost(self):
        """Get current product cost"""
        return self.product.price * self.quantity

karma_shop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name="name", max_length=64, unique=True)
    description = models.TextField(verbose_name="description", blank=True)

    def __str__(self):
        return self.name


class ProductBrand(models.Model):
    name = models.CharField(verbose_name="name", max_length=64, unique=True)
    description = models.TextField(verbose_name="description", blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='product name', max_length=64)
    brand_name = models.ForeignKey(ProductBrand, on_delete=models.SET_NULL, null=True)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='product short description', max_length=60, blank=True)
    description = models.TextField(verbose_name='product description', blank=True)
    price = models.DecimalField(verbose_name='product price', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='quantity in stock', default=0)

    def __str__(self):
        return f"{self.name} - Category:({self.category.name}); Brand: ({self.brand_name})"


class HotOffers(models.Model):
    title = models.CharField(verbose_name='product title', max_length=64)
    description = models.TextField(verbose_name='product description', max_length=200, blank=True)
    image = models.ImageField(upload_to='hot_offers_images', blank=True)

    def __str__(self):
        return f"Hot offer product name: {self.title}"


class DealsOfTheWeek(models.Model):
    name = models.CharField(verbose_name="product name", max_length=64)
    price = models.DecimalField(verbose_name="product name", max_digits=8, decimal_places=2, default=0)
    image = models.ImageField(verbose_name="product image", blank=True)
    url = models.URLField(verbose_name="product url", max_length=200, default="#")

    def __str__(self):
        return f"Deals of the week - Name: {self.name}; Price: {self.price}"


class SingleFeature(models.Model):
    name = models.CharField(verbose_name="feature name", max_length=64)
    short_desc = models.CharField(verbose_name="feature short description", max_length=64, blank=True)
    description = models.TextField(verbose_name="feature description", max_length=120, blank=True)
    image = models.ImageField(upload_to="single_feature_images", blank=True)

    def __str__(self):
        return f"Single features - Name: {self.name}"

karma_shop/mainapp/views.py
from django.shortcuts import render, get_object_or_404
from mainapp.models import ProductCategory, ProductBrand, Product, DealsOfTheWeek, SingleFeature


def get_related_products() -> list:
    deals_of_the_week = DealsOfTheWeek.objects.all()
    related_products = list()
    for deal in deals_of_the_week:
        related_products.append(deal)
    return related_products


def index(request):
    single_features = SingleFeature.objects.all()
    context = dict(
        related_products=get_related_products(),
        single_features=single_features,
    )
    return render(request, 'mainapp/index.html', context=context)


def products(request, *args, **kwargs):
    shop_products = Product.objects.all()
    context = dict(
        brands=ProductBrand.objects.all(),
        products=shop_products
    )
    return render(request, 'mainapp/category.html', context=context)


def category_items(request, category_pk=None, *args, **kwargs):
    category_products = Product.objects.filter(brand_name_id=category_pk)
    context = dict(
        brands=ProductBrand.objects.all(),
        products=category_products
    )
    return render(request, 'mainapp/category.html', context=context)


def product_page(request, product_pk=None):
    # context = dict(
    #     related_products=get_related_products(),
    #     page_title=single_product_data.get("page_title") or "Karma",
    #     product_description=single_product_data.get("product_description")
    # )
    product = get_object_or_404(Product, pk=product_pk)

    context = dict(
        product=product,
    )

    return render(request, 'mainapp/product_page.html', context=context)

karma_shop/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx" class="no-js">

<head>
	<!-- Mobile Specific Meta -->
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- Favicon-->
	<link rel="shortcut icon" href="{% static 'mainapp/img/fav.png' %}">
	<!-- Author Meta -->
	<meta name="author" content="CodePixar">
	<!-- Meta Description -->
	<meta name="description" content="">
	<!-- Meta Keyword -->
	<meta name="keywords" content="">
	<!-- meta character set -->
	<meta charset="UTF-8">
	<!-- Site Title -->
	<title>Karma</title>

    {% include 'mainapp/includes/styles/inc__cs.html' %}

</head>

<body>
	<!-- Start Header Area -->
	<header class="header_area sticky-header">
		<div class="main_menu">
			<nav class="navbar navbar-expand-lg navbar-light main_box">
				<div class="container">
					<!-- Brand and toggle get grouped for better mobile display -->
					<a class="navbar-brand logo_h" href="{% url 'main:index' %}"><img src="{% static 'mainapp/img/logo.png' %}" alt=""></a>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
					 aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
						{% for _ in '123'|make_list %}
                            <span class="icon-bar"></span>
                        {% endfor %}
					</button>
					<!-- Collect the nav links, forms, and other content for toggling -->
					<div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                        {% with active_page=request.resolver_match.url_name %}
						<ul class="nav navbar-nav menu_nav ml-auto">
							<li class="nav-item {% ifequal active_page 'index' %} active {% endifequal %}"><a class="nav-link" href="{% url 'main:index' %}">Home</a></li>
							<li class="nav-item submenu dropdown {% if active_page == 'catalog' or active_page == 'category_items' %} active {% endif %}">
								<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
								 aria-expanded="false">Shop</a>
								<ul class="dropdown-menu">
									<li class="nav-item {% ifequal active_page 'category' %} active {% endifequal %}"><a class="nav-link" href="{% url 'main:catalog' %}">Products</a></li>
{#									<li class="nav-item {% ifequal active_page 'single_product' %} active {% endifequal %}"><a class="nav-link" href="{% url 'main:single_product' %}">Product Details</a></li>#}
								</ul>
							</li>
                            {% if user.is_authenticated %}
                                <li class="nav-item submenu dropdown {% if active_page == 'register' or active_page == 'edit' %} active {% endif %}">
                                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                                     aria-expanded="false">
                                        {{ user.username|default:'Incognito' }}
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li class="nav-item {% ifequal active_page 'edit' %} active {% endifequal %}">
                                            <a class="nav-link" href="{% url 'auth:edit' %}">
                                                Edit
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="{% url 'auth:logout' %}">
                                                Logout
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                            {% else %}
                                <li class="nav-item"><a class="nav-link" href="{% url 'auth:register' %}">Register</a></li>
                            {% endif %}
                            {% if not user.is_authenticated %}
                                <li class="nav-item {% ifequal active_page 'login' %} active {% endifequal %}">
                                    <a class="nav-link" href="{% url 'auth:login' %}">
                                        Login
                                    </a>
                                </li>
                            {% endif %}
						</ul>
						<ul class="nav navbar-nav navbar-right">
							<li class="nav-item">
                                <a href="{% url 'basket:index' %}" class="cart"><span class="ti-bag"></span> {{ user.basket_set.count }}</a>
                            </li>
							<li class="nav-item">
								<button class="search"><span class="lnr lnr-magnifier" id="search"></span></button>
							</li>
						</ul>
                        {% endwith %}
					</div>
				</div>
			</nav>
		</div>
		<div class="search_input" id="search_input_box">
			<div class="container">
				<form class="d-flex justify-content-between">
					<input type="text" class="form-control" id="search_input" placeholder="Search Here">
					<button type="submit" class="btn"></button>
					<span class="lnr lnr-cross" id="close_search" title="Close Search"></span>
				</form>
			</div>
		</div>
	</header>
	<!-- End Header Area -->

    {% block everything_else %}
    {% endblock %}

    {% include 'mainapp/includes/inc__related_product.html' %}

	<!-- start footer Area -->
	<footer class="footer-area section_gap">
		<div class="container">
			<div class="row">
				<div class="col-lg-3  col-md-6 col-sm-6">
					<div class="single-footer-widget">
						<h6>About Us</h6>
						<p>
							Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore dolore
							magna aliqua.
						</p>
					</div>
				</div>
				<div class="col-lg-4  col-md-6 col-sm-6">
					<div class="single-footer-widget">
						<h6>Newsletter</h6>
						<p>Stay update with our latest</p>
						<div class="" id="mc_embed_signup">

							<form target="_blank" novalidate="true" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
							 method="get" class="form-inline">

								<div class="d-flex flex-row">

									<input class="form-control" name="EMAIL" placeholder="Enter Email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Email '"
									 required="" type="email">

									<button class="click-btn btn btn-default"><i class="fa fa-long-arrow-right" aria-hidden="true"></i></button>
									<div style="position: absolute; left: -5000px;">
										<input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">
									</div>

								</div>
								<div class="info"></div>
							</form>
						</div>
					</div>
				</div>
				<div class="col-lg-3  col-md-6 col-sm-6">
					<div class="single-footer-widget mail-chimp">
						<h6 class="mb-20">Instragram Feed</h6>
						<ul class="instafeed d-flex flex-wrap">
                            {% for i in '12345678'|make_list %}
                                {% with 'mainapp/img/i'|add:i|add:'.jpg' as image_name %}
							        <li><img src="{% static image_name %}" alt=""></li>
                                {% endwith %}
                            {% endfor %}
						</ul>
					</div>
				</div>
				<div class="col-lg-2 col-md-6 col-sm-6">
					<div class="single-footer-widget">
						<h6>Follow Us</h6>
						<p>Let us be social</p>
						<div class="footer-social d-flex align-items-center">
                            <a href=""><i class="fa fa-facebook"></i></a>
                            <a href=""><i class="fa fa-twitter"></i></a>
                            <a href=""><i class="fa fa-dribbble"></i></a>
							<a href=""><i class="fa fa-behance"></i></a>
						</div>
					</div>
				</div>
			</div>
			<div class="footer-bottom d-flex justify-content-center align-items-center flex-wrap">
				<p class="footer-text m-0"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
</p>
			</div>
		</div>
	</footer>
	<!-- End footer Area -->

    {% include 'mainapp/includes/styles/inc__js.html' %}
</body>

</html>

karma_shop/templates/mainapp/category.html
{% extends 'mainapp/base.html' %}
{% load static %}

    {% block everything_else %}

	<!-- Start Banner Area -->
	<section class="banner-area organic-breadcrumb">
		<div class="container">
			<div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
				<div class="col-first">
					<h1>Shop Category page</h1>
					<nav class="d-flex align-items-center">
						<a href="{% url 'main:index' %}">Home<span class="lnr lnr-arrow-right"></span></a>
						<a href="">Shop<span class="lnr lnr-arrow-right"></span></a>
						<a href="{% url 'main:catalog' %}">Fashon Category</a>
					</nav>
				</div>
			</div>
		</div>
	</section>
	<!-- End Banner Area -->

    <!-- Filter Bar -->
	<div class="container">
		<div class="row">
			<div class="col-xl-3 col-lg-4 col-md-5">
<!--
Закоментировал, т.к. теперь данные тяну из бд, а не из json. Поэтому этот блок сломается
Раскоментировать его после того, как пойму как делать фильтры выпадающих списков
-->
{#				<div class="sidebar-categories">#}
{#					<div class="head">Browse Categories</div>#}
{#					<ul class="main-categories">#}
{#                        {% for category in categories %}#}
{#                            <li class="main-nav-list"><a data-toggle="collapse" href="{{ category.url }}" aria-expanded="false" aria-controls="{{ category.aria_controls }}"><span#}
{#                                     class="lnr lnr-arrow-right"></span>{{ category.name }}<span class="number">({{ category.quantity }})</span></a>#}
{#                                <ul class="collapse" id="{{ category.id }}" data-toggle="collapse" aria-expanded="false" aria-controls="{{ category.aria_controls }}">#}
{#                                    {% for sub_category in category.sub_categories %}#}
{#                                        <li class="main-nav-list child"><a href="{{ sub_category.url }}">{{ sub_category.name }}<span class="number">({{ sub_category.quantity }})</span></a></li>#}
{#                                    {% empty %}#}
{#                                        <li class="main-nav-list child">Loading category. Please wait...</li>#}
{#                                    {% endfor %}#}
{#                                </ul>#}
{#                            </li>#}
{#                        {% empty %}#}
{#                            <li class="main-nav-list">Loading category. Please wait...</li>#}
{#                        {% endfor %}#}
{#					</ul>#}
{#				</div>#}
                <!--BRAND-->
				<div class="sidebar-filter mt-50">
					<div class="top-filter-head">Product Filters</div>
                        <div class="common-filter">
                            <div class="head">BRAND</div>
                            <form action="#">
                                <ul>
                                    {% for brand in brands %}
                                        <li class="filter-list">
{#                                            <input class="pixel-radio" type="radio" name="brand">#}
                                                {% with brand_id=brand.id %}
                                                    <a href='{% url 'main:category_items' brand_id %}'>{{ brand.name }}</a>
                                                {% endwith %}
                                        </li>
                                    {% endfor %}
                                </ul>
                            </form>
                        </div>
{#Убираю фильтр по цвету (временно)#}
{#                        <div class="common-filter">#}
{#                            <div class="head">{{ product_filter.filter_category_name }}</div>#}
{#                            <form action="#">#}
{#                                <ul>#}
{#                                    {% for filter in product_filter.filters %}#}
{#                                        <li class="filter-list">#}
{#                                            <input class="pixel-radio" type="radio" id="{{ filter.id }}" name="{{ product_filter.sub_filter_name_tag }}">#}
{#                                            <label for="{{ filter.label }}">#}
{#                                                <a href='#'>{{ filter.name }}</a>#}
{#                                                <span>#}
{#                                                    ({{ filter.quantity }})#}
{#                                                </span>#}
{#                                            </label>#}
{#                                        </li>#}
{#                                    {% endfor %}#}
{#                                </ul>#}
{#                            </form>#}
{#                        </div>#}
					<div class="common-filter">
						<div class="head">Price</div>
						<div class="price-range-area">
							<div id="price-range"></div>
							<div class="value-wrapper d-flex">
								<div class="price">Price:</div>
								<span>$</span>
								<div id="lower-value"></div>
								<div class="to">to</div>
								<span>$</span>
								<div id="upper-value"></div>
							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="col-xl-9 col-lg-8 col-md-7">
				<!-- Start Filter Bar -->
{#				<div class="filter-bar d-flex flex-wrap align-items-center">#}
{#					<div class="sorting">#}
{#						<select>#}
{#							<option value="1">Sort by price</option>#}
{#							<option value="1">Sort by date</option>#}
{#							<option value="1">Sort by popularity</option>#}
{#						</select>#}
{#					</div>#}
{#					<div class="sorting mr-auto">#}
{#						<select>#}
{#							<option value="1">Show 12</option>#}
{#							<option value="1">Show 24</option>#}
{#							<option value="1">Show 36</option>#}
{#						</select>#}
{#					</div>#}
{#					<div class="pagination">#}
{#						<a href="#" class="prev-arrow"><i class="fa fa-long-arrow-left" aria-hidden="true"></i></a>#}
{#						<a href="#" class="active">1</a>#}
{#						<a href="#">2</a>#}
{#						<a href="#">3</a>#}
{#						<a href="#" class="dot-dot"><i class="fa fa-ellipsis-h" aria-hidden="true"></i></a>#}
{#						<a href="#">6</a>#}
{#						<a href="#" class="next-arrow"><i class="fa fa-long-arrow-right" aria-hidden="true"></i></a>#}
{#					</div>#}
{#				</div>#}
				<!-- End Filter Bar -->

				<!-- Start Best Seller -->
				<section class="lattest-product-area pb-40 category-list">
					<div class="row">
						<!-- single product -->
                        {% for product in products %}
						<div class="col-lg-4 col-md-6">
							<div class="single-product">
								<img class="img-fluid" src="{{ product.image.url }}" alt="">
								<div class="product-details">
									<a href="{% url "main:product_page" product_pk=product.id %}"><h6>{{ product.name }}</h6></a>
									<div class="price">
{#										<h6 class="l-through">${{ product.price_for_sale }}</h6>#}
										<h6>${{ product.price }}</h6>
									</div>
									<div class="prd-bottom">

										<a href="{% url 'basket:add' product_pk=product.pk %}" class="social-info">
											<span class="ti-bag"></span>
											<p class="hover-text">add to bag</p>
										</a>
										<a href="" class="social-info">
											<span class="lnr lnr-heart"></span>
											<p class="hover-text">Wishlist</p>
										</a>
										<a href="" class="social-info">
											<span class="lnr lnr-sync"></span>
											<p class="hover-text">compare</p>
										</a>
										<a href="" class="social-info">
											<span class="lnr lnr-move"></span>
											<p class="hover-text">view more</p>
										</a>
									</div>
								</div>
							</div>
						</div>
                        {% endfor %}
					</div>
				</section>
				<!-- End Best Seller -->

			</div>
		</div>
	</div>

    {% endblock %}

karma_shop/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block everything_else %}

<!-- start banner Area -->
<section class="banner-area">
    <div class="container">
        <div class="row fullscreen align-items-center justify-content-start">
            <div class="col-lg-12">
                <div class="active-banner-slider owl-carousel">
                    <!-- single-slide -->
                    {% for i in '12'|make_list %}
                    <div class="row single-slide align-items-center d-flex">
                        <div class="col-lg-5 col-md-6">
                            <div class="banner-content">
                                <h1>Nike New <br>Collection!</h1>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p>
                                <div class="add-bag d-flex align-items-center">
                                    <a class="add-btn" href="#"><span class="lnr lnr-cross"></span></a>
                                    <span class="add-text text-uppercase">Add to Bag</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-7">
                            <div class="banner-img">
                                <img class="img-fluid" src="{% static 'mainapp/img/banner/banner-img.png' %}" alt="">
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End banner Area -->

<!-- start features Area -->
<section class="features-area section_gap">
    <div class="container">
        <div class="row features-inner">
            {% for single_feature in single_features %}
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="single-features">
                        <div class="f-icon">
                            <img src="{{ single_feature.image.url }}" alt="">
                        </div>
                        <h6>{{ single_feature.short_desc }}</h6>
                        <p>{{ single_feature.description }}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</section>
<!-- end features Area -->

<!-- Start brand Area -->
<section class="brand-area section_gap">
    <div class="container">
        <div class="row">
            {% for i in '12345'|make_list %}
                {% with image_path='mainapp/img/brand/'|add:i|add:'.png' %}
                    <a class="col single-img" href="#">
                        <img class="img-fluid d-block mx-auto" src="{% static image_path %}" alt="">
                    </a>
                {% endwith %}
            {% endfor %}
        </div>
    </div>
</section>
<!-- End brand Area -->
{% endblock %}

karma_shop/templates/mainapp/product_page.html
{% extends 'mainapp/base.html' %}
{% load static %}

    {% block everything_else %}

	<!-- Start Banner Area -->
	<section class="banner-area organic-breadcrumb">
		<div class="container">
			<div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
				<div class="col-first">
					<h1>Product page</h1>
					<nav class="d-flex align-items-center">
						<a href="{% url 'main:index' %}">Home<span class="lnr lnr-arrow-right"></span></a>
						<a href="{% url 'main:catalog' %}">Shop<span class="lnr lnr-arrow-right"></span></a>
						<a href="">Product page</a>
					</nav>
				</div>
			</div>
		</div>
	</section>
	<!-- End Banner Area -->

	<!--================Single Product Area =================-->
	<div class="product_image_area offset-lg-1">
		<div class="container">
			<div class="row s_product_inner">
				<div class="col-lg-6">
					<div class="s_Product_carousel">
{#                    ToDo Сделать тут разные изображения продукта#}
                        {% for i in '123'|make_list %}
                            <div class="single-prd-item">
                                <img class="img-fluid" src="{{ product.image.url }}" alt="">
                            </div>
                        {% endfor %}
					</div>
				</div>
				<div class="col-lg-5 offset-lg-1">
					<div class="s_product_text">
						<h3><span class="product_name">{{ product.name }}</span></h3>
						<h2><span class="product_price">${{ product.price }}</span></h2>
						<ul class="list">
							<li><a class="product_category active" href="{% url "main:category_items" category_pk=product.category_id %}"><span>Category</span> : {{ product.category }}</a></li>
                            <li>
                                <a href="#"><span>Availibility</span>
                                    {% if product.quantity > 0 %}
                                        : In Stock ({{ product.quantity }})
                                    {% else %}
                                        : Out of Stock
                                    {% endif %}
                                </a>
                            </li>
						</ul>
						<p>{{ product.short_desc }}</p>
{#                        Кнопка выбора количества товара для добавления в корзину#}
{#						<div class="product_count">#}
{#							<label for="qty">Quantity:</label>#}
{#							<input type="text" name="{{ product.pk }}" id="sst" maxlength="3" value="1" title="Quantity:" class="input-text qty">#}
{#							<button onclick="var result = document.getElementById('sst'); var sst = result.value; if( !isNaN( sst )) result.value++;return false;"#}
{#							 class="increase items-count" type="button"><i class="lnr lnr-chevron-up"></i></button>#}
{#							<button onclick="var result = document.getElementById('sst'); var sst = result.value; if( !isNaN( sst ) &amp;&amp; sst > 0 ) result.value--;return false;"#}
{#							 class="reduced items-count" type="button"><i class="lnr lnr-chevron-down"></i></button>#}
{#						</div>#}
						<div class="card_area d-flex align-items-center">
							<a class="primary-btn" href="{% url 'basket:add' product_pk=product.id %}">Add to Cart</a>
							<a class="icon_btn" href=""><i class="lnr lnr lnr-heart"></i></a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!--================End Single Product Area =================-->

    {% endblock %}